export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILUER = 'FETCH_PRODUCT_FAILUER'
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const API_PENDING='SERVICE_PENDING'
export const API_SUCCESS='SERVICE_SUCCESS'
export const API_ERROR = 'SERVICE_ERROR'
export const GET_COROSAL_IMAGE = 'gET_COROSAL_IMAGE';

export const GET_COROSAL_IMAGE_FULFILLED = 'GET_COROSAL_IMAGE_FULFILLED';

export const GET_COROSAL_IMAGE_REJECTED = 'GET_COROSAL_IMAGE_REJECTED';