export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILUER = 'FETCH_PRODUCT_FAILUER'
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const API_PENDING = 'SERVICE_PENDING'
export const API_SUCCESS = 'SERVICE_SUCCESS'
export const API_ERROR = 'SERVICE_ERROR'
export const GET_COROSAL_IMAGE = 'gET_COROSAL_IMAGE';

export const GET_COROSAL_IMAGE_FULFILLED = 'GET_COROSAL_IMAGE_FULFILLED';

export const GET_COROSAL_IMAGE_REJECTED = 'GET_COROSAL_IMAGE_REJECTED';

export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE'

export const ADD_TO_CARD = "ADD_TO_CARD"
export const REMOVE_FROM_CARD = "REMOVE_FROM_CARD"
export const FETCH_ADDRESS = 'FETCH_ADDRESS'
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS'
export const FETCH_ADDRESS_FAILUER = 'FETCH_ADDRESS_FAILUER'